import openai 
openai.api_key = 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
response = openai.ChatCompletion.create(model="gpt-4-turbo", messages=messages)
